spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    ddl-auto: create-drop
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect